### ISSUE TITLE
Remove Authorization PopUp

### ISSUE THREAD

**Issue by malavagile** [sveinbjornt/STPrivilegedTask#10]
Hello ,

I am using your Code to run my ShellScript. 
This is how I used the code.

STPrivilegedTask *taskToRemoveHelperTool = [STPrivilegedTask launchedPrivilegedTaskWithLaunchPath:pathForUninstallFile arguments:[NSArray arrayWithObjects:@"Uninstall.sh", nil]];

But it ask user to enter password. If this is running as root then why it needs user's password?

My main purpose is to execute this shell script without Authorization PopUp.

Thanks

**Comment by sveinbjornt** [comment]
In order to run code with admin privileges through Apple's Security framework, a user must authenticate himself. This is done by making him enter his password. That is how these things work.
