### ISSUE TITLE
Wrong terminationStatus

### ISSUE THREAD

**Issue by anton-simakov** [sveinbjornt/STPrivilegedTask#14]
I noticed that my task reports a wrong terminationStatus. I think the problem is in this code `waitpid(_processIdentifier, &_terminationStatus, 0);` To get the status information it is necessary to use `WEXITSTATUS` macros.

**Comment by anton-simakov** [comment]
Hi,

Thanks for the fix. It seems there is one more place that needs to be patched:

```
- (void)waitUntilExit
{
    waitpid(_processIdentifier, &_terminationStatus, 0);
    _isRunning = NO;
}
```

**Comment by sveinbjornt** [comment]
Fixed in master, making a new release.

**Comment by anton-simakov** [comment]
Thanks!
