### ISSUE TITLE
Something went wrong: -60005

### ISSUE THREAD

**Issue by kapil0408** [sveinbjornt/STPrivilegedTask#17]
I am running this code on 10.11.6. but it is showing error.
error:

Something went wrong: -60005
Task <STPrivilegedTask: 0x60000009cc50> is not running
outputString=

Code:
STPrivilegedTask *task = [[STPrivilegedTask alloc] init];
    [task setLaunchPath:@"/usr/bin/pluginkit"];
    [task setArguments: @[@"-vmA"]];
    [task setCurrentDirectoryPath:[[NSBundle mainBundle] resourcePath]];
    
    OSStatus err = [task launch];
    if (err != errAuthorizationSuccess) {
        if (err == errAuthorizationCanceled) {
            NSLog(@"User cancelled");
            return;
        }  else {
            NSLog(@"Something went wrong: %d", (int)err);
            // For error codes, see http://www.opensource.apple.com/source/libsecurity_authorization/libsecurity_authorization-36329/lib/Authorization.h
        }
    }
    
    [task waitUntilExit];
    
    NSFileHandle *readHandle = [task outputFileHandle];
    NSData *outputData = [readHandle readDataToEndOfFile];
    NSString *outputString = [[NSString alloc] initWithData:outputData encoding:NSUTF8StringEncoding];
    NSLog(@"outputString=%@",outputString);

Please any suggestion or comment on it.

Thanks & Regards

**Comment by sveinbjornt** [comment]
-60005 is errAuthorizationDenied

**Comment by kapil0408** [comment]
but when i run this command using NSTask and without Sandbox. it is showing results fine and no error occurs.
but using in Sandbox it is not showing any results. 

is there any other approach where i can find using NSTask with Sandbox?

Thanks

**Comment by wentingliu** [comment]
There is no way to acquire root privilege when your app is in sandbox.
