### ISSUE TITLE
how to input Authorization password only one time ? 

### ISSUE THREAD

**Issue by MelissaShu** [sveinbjornt/STPrivilegedTask#18]
how to input Authorization password only one time ? 
If I run more shell with root, I have to input password many times. Can I make it better ?

**Comment by sveinbjornt** [comment]
This is currently not possible using STPrivilegedTask but you can always use the Authorization Framework directly. An example of reusing an AuthorizationRef is provided in another software project of mine, Sloth. See https://github.com/sveinbjornt/Sloth/blob/master/source/SlothController.m
