### ISSUE TITLE
isExecutableFileAtPath always return no

### ISSUE THREAD

**Issue by Lilung-Chao** [sveinbjornt/STPrivilegedTask#21]
When I call the method "- (BOOL)isValidShellCommand:(NSString *)cmd
" the shell command(/usr/local/bin/ideviceinfo)  always return NO, but use the example project can return YES. This command has been installed in (/usr/local/bin/) directory, but my project can not found the executable file. Compared my project file settings and info.plist file, I can not find the different with the example project. How can I setup the project, make the executable file can be found. Thanks.

**Comment by sveinbjornt** [comment]
Just don't call the validation function and try again. Does the binary have execute permissions? Try chmod +x /usr/local/bin/ideviceinfo.
