### ISSUE TITLE
How to catch stderr log?

### ISSUE THREAD

**Issue by Fidetro** [sveinbjornt/STPrivilegedTask#25]
When I use stdout everything works fine, but currently it doesn't seem to be able to capture the stderr output? I see the commented out code `AuthorizationExecuteWithPrivilegesStdErrAndPid`, does it work?

**Comment by sveinbjornt** [comment]
This is a limitation of the AuthorizationExecuteWithPrivileges function. You can work around it by running your process in a shell script that redirects stderr to stdout. I don't remember if that old, commented-out function works but that's basically what it does. You can give it a try.
